### ISSUE TITLE
MySQL_Inband and MSSQL_Inband methods return magled queries

### ISSUE THREAD

**Issue by matisec** [lanjelot/albatar#1]
Some queries predefined in MySQL_Inband and MSSQL_Inband classes are mangled and fail to yield correct value when albatar is run with the corresponding command line parameters eg.:

656: class MySQL_Inband(SQLi_Base):
657:
658: def banner(self):
659:     return '(SELECT VERSION() X)a'
[...]
733: class MySQL_Blind(SQLi_Base):
734:   
735:   def banner(self):
736:     return 'SELECT VERSION()'

**Comment by lanjelot** [comment]
no idea what you mean, please submit patch
